#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker tag sails-rest-api:created_in_travis-ci  yarbel82/sails-rest-api:created_in_travis-ci
docker push yarbel82/sails-rest-api:created_in_travis-ci
